import type { Metadata } from 'next'
import { Neucha } from 'next/font/google'
import '@/app/globals.css';

const neucha = Neucha({ weight: '400', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={neucha.className}>{children}</body>
    </html>
  )
}
